### ISSUE TITLE
Use human-readable pattern category name

### ISSUE THREAD

**Issue by colorful-tones** [studiopress/pattern-manager#105]
If you register a custom pattern category using `register_block_pattern_category()` then in Pattern Manager it uses `ucwords()` on the machine-readable name, whereas it would be more suitable to just use the human-readable name.

I believe this is happening here in Pattern Manager: https://github.com/studiopress/pattern-manager/blob/0a551713d18e5e259bde4fd3beeeedb48e6040f9/wp-modules/editor/editor.php#L299

## Steps to recreate

Place this in a `functions.php` or wherever:

```
function acf_recipes_block_pattern_category() {
	register_block_pattern_category(
		'acf-recipe-patterns',
		array(
			'label' => __( 'Recipes', 'acf-recipes' ),
		)
	);
}
add_action( 'init', 'acf_recipes_block_pattern_category' );
```

You should see this output in Pattern Manager sidebar

![Screen Shot 2023-03-10 at 5 11 06 PM](https://user-images.githubusercontent.com/405912/224438781-fc8f9956-d03f-4c28-9cf4-bcdcf11fe51b.png)

**Comment by mike-day** [comment]
Closing this issue as the aforementioned `register_block_patterns()` call on `current-screen` has been removed.
