### ISSUE TITLE
Can't edit meta before pattern created

### ISSUE THREAD

**Issue by kienstra** [studiopress/pattern-manager#166]
**Describe the bug**
In a new pattern, you can't edit meta before you've clicked 'Create Pattern'

**To Reproduce**
Thanks to Mike Day for these steps

1. Go to `/wp-admin/post-new.php?post_type=pm_pattern`
2. Only add a category
3. Click 'Create Pattern':

<img width="610" alt="Screenshot 2023-05-12 at 12 51 25 PM" src="https://github.com/studiopress/pattern-manager/assets/4063887/5abfb677-6e96-456e-be08-bc97440c91ef">

4. Expected: The category persists 
5. Actual: The category is gone: 
<img width="612" alt="Screenshot 2023-05-12 at 12 53 29 PM" src="https://github.com/studiopress/pattern-manager/assets/4063887/a3dc3b90-ea9a-42e0-a883-01f29ff98e4f">

**Device and browser information**
 - OS: Not important
 - Browser: Not important
 - Version 0.2.2

**Comment by mike-day** [comment]
Thanks for adding this, @kienstra!

**Comment by kienstra** [comment]
Of course, thanks for finding it

**Comment by kienstra** [comment]
I probably introduced this [in 0.1.8](https://github.com/studiopress/pattern-manager/compare/0.1.7...0.1.8)
