### ISSUE TITLE
Patternception Block doesn't render preview if Pattern's slug doesn't match its filename

### ISSUE THREAD

**Issue by johnstonphilip** [studiopress/pattern-manager#172]
**Describe the bug**
The Pattern Block (aka the Patternception block) will not render a preview of the "child" block if that block's slug doesn't match its title.

**To Reproduce**
1. Install the twentytwentythree theme.
2. Create a new Pattern.
3. Add the "Pattern Block" and pick the "Call to Action" pattern.
4. Save.
5. Refresh. Notice nothing broke yet
6. Now, go an edit something about the "child" pattern. Save.
7. In the parent pattern, the preview won't show because **the slug of the child was changed** (even though you didn't change that), meaning the slug saved to the parent's attributes is no longer valid.

**Comment by kienstra** [comment]
Ah, that's important:

>…because the slug of the child was changed (even though you didn't change that), meaning the slug saved to the parent's attributes is no longer valid.
