### ISSUE TITLE
Version control notice ignores higher level version control

### ISSUE THREAD

**Issue by bacoords** [studiopress/pattern-manager#194]
**Describe the bug**
The new version control notice shows up if you're not tracking the theme directory. However many workflows, including WP Engine's Git Push, have version control starting at the root dir of WordPress rather than the theme folder.

**To Reproduce**
1. Initialize Git at a higher directory than the theme, say the main wp folder
2. See the notice is still there

**Expected behavior**
I guess I'd expect it to be aware of parent directories at least up to the root wp folder.

**Screenshots**

**Version**
- 0.2.0

**Device and browser information**
 - OS: MacOS
 - Browser: Arc 0.106.1 & Chrome 114.0.5735.106

**Comment by kienstra** [comment]
Hi @bacoords,
You're right, this should be aware of .git roots higher than the theme. 

Is dismissing the notice working alright for you? 

It shouldn't show again once you've dismissed it.

Thanks for opening this, and sorry for the delay.

**Comment by bacoords** [comment]
Yep the dismiss is working for me, though I imagine seeing the notice that first time will still trigger some anxiety for developers

**Comment by kienstra** [comment]
Thanks, you're right about that.

We'll keep this in mind, though to be honest we probably won't fix it in the next few months.

**Comment by kienstra** [comment]
To be honest, this issue is valid, but it's not a high enough priority to fix.
