### ISSUE TITLE
Add `.nvmrc` for better developer/contributor experience

### ISSUE THREAD

**Issue by colorful-tones** [studiopress/pattern-manager#58]
**Is your feature request related to a problem? Please describe.**

I went to spin up a copy of the repo and ran `npm install`, but was on the wrong version of Node. It is quite common to use NVM to manage and hot-swap Node versions. Furthermore, it is common to provide a `.nvmrc`, which tells NVM to swap to the desired Node version when switching to this project's repo. 

**Describe the solution you'd like**

Please consider adding a `.nvmrc` file in the root of this repo with the desired Node version. I assume it is `14` based on what the `.circleci` tooling is using [in `config.yml`](https://github.com/studiopress/pattern-manager/blob/main/.circleci/config.yml#L63)

**Describe alternatives you've considered**

No alternatives have been considered because this is a pretty wide standard.

Example projects that include a `.nvmrc` file:

- [Gutenberg](https://github.com/WordPress/gutenberg/blob/trunk/.nvmrc)
- [React](https://github.com/facebook/react/blob/main/.nvmrc)
- [Faust.js](https://github.com/wpengine/faustjs/blob/canary/.nvmrc)

**Additional context**

[Node Version Manager](https://github.com/nvm-sh/nvm) is bash script tooling to manage multiple active node.js versions. [Here is further info on the `.nvmrc` file](https://github.com/nvm-sh/nvm).

FWIW - I was going to follow up with a PR, but I don't have `write` access to push up a branch. Thanks Team Gen! 🤘

**Comment by kienstra** [comment]
Thanks for opening this. It was fixed in https://github.com/studiopress/pattern-manager/pull/184.
